### ISSUE TITLE
Update to use STM32CubeMX CMake generation

### ISSUE THREAD

**Issue by BlakeFreer** [macformula/racecar#140]
Our build system currently uses the Makefile generated by CubeMX when building a project for the STM32 platform. Ex, go into `racecar/firmware` and run

```bash
make PROJECT=Demo/Blink PLATFORM=stm32f677
```

Eventually, CMake reaches the `firmware/projects/Demo/Blink/platforms/stm32f767/cubemx/CMakeLists.txt` which includes `firmware/cmake/build_cubemx.cmake`.

`build_cubem.cmake` first calls `firmware/cmake/generate_cubemx.mk` to regenerate code from CubeMX if the `board_config.ioc` file is newer than the `Makefile` generated by CubeMX. We then append some custom targets to that makefile which allows us to extract variables rfom it into CMake, all so that we can compile the CubeMX source files in CMake. It is a big mess.

STM32CubeMX can now generate for CMake directly which will cut out most of this mess.

# Task

You will prototype on the `Demo/Blink` project.

1. Convert the project to generate for CMake instead of Makefile. To change this option, open the `.ioc` file in CubeMX and go to the Project Management tab.
2. Generate the code. Document what the CMake project looks like.
3. Link the CMake target to main in `platforms/stm32f767/CMakeLists.txt`. You are replacing what is currently the `driver` library target. You are free to edit the `platforms/stm32f767/cubemx/CMakeLists.txt` and `firmware/cmake/build_cubemx,cmake` files if necessary.
4. Show that the system builds properly.
5. Document the CMake integration in Markdown to add to <https://macformula.github.io/racecar/firmware/>

# Notes

We currently use a Makefile `generate_cubemx.mk` rather than CMake to generate code from CubeMX. This is because, with the current setup, the generation must occur at CMake "configure" time such that the sources are known before starting CMake's "build" stage. Using a separate Makefile is what allows us to only regenerate when `board_config` is updated. If you can integrate all of this in CMake, then great, but only if you ensure that CubeMX only generates when necessary (as this is a very slow process).

**Comment by Corbin-Jarrett** [comment]
I have been able to generate files using Cmake in STM32CubeMX. Some relevant differences between make:
1. The obvious difference, no Makefile is generated. Instead, a `cmake` directory is created.
2. This directory has a file `gcc-arm-none-eabi.cmake`
3. It also has a subdirectory `stm32cubemx` which contains `CMakeLists.txt`. I believe this file is a suitable replacement for `driver`

I have been able to get the build system to find and link the new driver library, now called `stm32cubemx`. I have reason to believe this is working because `bindings.cc` successfully builds. See attachment.
![image](https://github.com/user-attachments/assets/0ba4e299-0edd-4895-9cff-bcad7109cdca)

I am working through build errors with other files now. I am also unsure about how to go about regenerating only when `board_config` is updated. I will keep looking into this.

**Comment by BlakeFreer** [comment]
> I have reason to believe this is working because bindings.cc successfully builds

This may not mean it is working since a lot of `bindings` relates to the linking process, so you'll know it worked once you see `linking bindings.cc` or something similar

> I am also unsure about how to go about regenerating only when board_config is updated

Don't worry about this. It can stay in a Makefile for now since _how_ we generate the code is less important than _what code_ is generated. You can assume the code is generated, your task is to integrate the generated CMake targets
